export const WORKLIST_SUCCESS = 'WORKLIST_SUCCESS';
export const WORKLIST_ERROR = 'WORKLIST_ERROR';

export const FILTER_WORKLIST_DATA_SUPPLIER = 'FILTER_WORKLIST_DATA_SUPPLIER';
export const FILTER_WORKLIST_DATA_SDTYPE = 'FILTER_WORKLIST_DATA_SDTYPE';

export const SEARCH_WORKLIST_DATA_OFFLINE = 'SEARCH_WORKLIST_DATA_OFFLINE';
export const SEARCH_WORKLIST_DATA_ONLINE_SUCCESS = 'SEARCH_WORKLIST_DATA_ONLINE_SUCCESS';
export const SEARCH_WORKLIST_DATA_ONLINE_ERROR = 'SEARCH_WORKLIST_DATA_ONLINE_ERROR';

export const FILTER_WORKLIST_DATA_RESET = 'FILTER_WORKLIST_DATA_RESET';

export const SET_CURRENT_WORKLIST_SUCCESS = 'SET_CURRENT_WORKLIST_SUCCESS';
export const SET_CURRENT_WORKLIST_ERROR = 'SET_CURRENT_WORKLIST_ERROR';
